### ISSUE TITLE
牛X，赞一个！

### ISSUE THREAD

**Issue by rockswang** [songguoxiong/wsjs_saic_crack#1]

**Comment by songguoxiong** [comment]
谢谢，从你的文章里学到了很多相关思路

**Comment by Biubiu0329** [comment]
想问问你们有测试成功吗？我返回的怎么是空？？616637861

**Comment by Uukins** [comment]
请问更新了吗

**Comment by songguoxiong** [comment]
> 想问问你们有测试成功吗？我返回的怎么是空？616637861



> 请问更新了吗

商标网8月初已经更新新一套的加密，我这边的加密已经失效。

**Comment by Uukins** [comment]
谢谢你的回复,请问破解周期一般是多长时间,想学但是不知道从哪下手,你的代码还会更新吗

**Comment by songguoxiong** [comment]
> 谢谢你的回复,请问破解周期一般是多长时间,想学但是不知道从哪下手,你的代码还会更新吗

周期每个人都不一样，如果你之前没接触过瑞数，那建议你使用puppeteer或其他类似的自动化工具入手了。
商标网更新很频繁，这不是一个长期维护的项目，只能说随缘更新了。

**Comment by Uukins** [comment]
了解!我这两星期用selenium+Firefox弄了四五千条数据,代理不一定能进到网页里面,就算进去也不一定保证过程不会被ban,效率太低了,基本上放弃浏览器模拟了,然后尝试puppeter+chromium,一进去就被BAN,和用selenium+Chrome不设置开发者模式一样,哈哈哈....太绝了
